name: Kotlin Maven CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build and Test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]  # You can add more OS if needed.

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '17'   # You can use 11 or any version that suits your project.

    - name: Cache Maven dependencies
      uses: actions/cache@v3
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-
    - name: Install Maven dependencies
      run: mvn install -DskipTests

    - name: Build and Run Tests
      run: mvn test

  deploy:
    name: Deploy to Local Mac
    runs-on: ubuntu-latest
    needs: build  # Deploy only after the build job succeeds

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set up SSH Key
      run: |
          mkdir -p ~/.ssh/
          echo "$SSH_KEY" > ../private.key
          sudo chmod 600 ../private.key
          echo "$SSH_HOSTS" > ~/.ssh/known_hosts
      shell: bash
      env:
         SSH_PRIVATE_KEY: ${{secrets.SSH_KEY}}
         SSH_KNOWN_HOSTS: ${{secrets.SSH_HOST}}
         SSH_KEY_PATH: ${{ github.workspace }}/../private.key

    - name: Deploy Files to Local Mac
      run: |
        rsync -avz --delete ./ ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:/Users/valentinakond/Desktop/deploy
