name: Kotlin Maven CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build and Test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]  # You can add more OS if needed.

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '17'   # You can use 11 or any version that suits your project.

    - name: Cache Maven dependencies
      uses: actions/cache@v3
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-

    - name: Install Maven dependencies
      run: mvn install -DskipTests

    - name: Build and Run Tests
      run: mvn test

  deploy:
    name: Deploy to Remote Server
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    needs: build
    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Deploy via SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.DEPLOY_KEY }}

# Добавляем сервер в хосты, которым можно доверять
    - name: Add server to known_hosts
      run: |
        ssh-keyscan -H ${{ secrets.DEPLOY_HOST }} >> ~/.ssh/known_hosts
# Заливаем файлы на виртуальную машину
    - name: Copy files to the local Mac machine
      if: runner.os == 'Linux'
      run: |
        rsync -avz --delete ./ ${{ secrets.DEPLOY_HOST }}@${{ secrets.DEPLOY_SERVER }}:/Users/ruslanagaev/Desktop/deploy
